all: test_1 test_2 test_3

test_1: test-threads_1.c
	gcc -o test_1 test-threads_1.c -lpthread

test_2: test-threads_2.c
	gcc -o test_2 test-threads_2.c -lpthread

test_3: test-threads_3.c
	gcc -o test_3 test-threads_3.c -lpthread